version: '3.7'

services:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - 8000:80
    restart: always
    volumes:
      - /tmp:/tmp
    links:
      - mysqldb
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: 123456
      PMA_HOST: mysqldb
    networks:
      - code-network

# PHP - Apache - ambiente desenvolvimento.
  php-apache:
    container_name: php-apache
    restart: always
    build:
      context: ./files/php-apache
      args:
        URL_PROXY: ${URL_PROXY}
        PHP_VERSION: ${PHP_VERSION}
        HOME: ${HOME_DIR}
    volumes:
      - ${HOME_DIR}/discoDocker/apache/projetos/:/var/www/html/
      - ${HOME_DIR}/discoDocker/apache/conf/:/etc/apache2/sites-available/
    #      - ${HOME_DIR}/discoDocker/apache/logs/:/var/log/apache2
      - /tmp:/tmp
    ports:
      - 80:80
    links:
      - mysqldb
      - memcached
    networks:
      - code-network

  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    restart: always
    command: ['mysqld', '--lower_case_table_names=0', '--default_authentication_plugin=mysql_native_password']
    volumes:
      - mysqldb_data:/var/lib/mysql
      - /tmp:/tmp
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    networks:
      - code-network

  memcached:
    container_name: memcached
    restart: always
    image: memcached:latest
    ports:
      - 11211:11211
    networks:
      - code-network

#  Gerenciador de Container.
  portainer:
    image: portainer/portainer
    ports:
      - 9000:9000
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - code-network

  # SMTP Server - desenvolvimento. (MailHog)
  maillocal:
    container_name: maillocal
    restart: always
    build:
      context: ./files/mailhog
      args:
        URL_PROXY: ${URL_PROXY}
        PHP_VERSION: ${PHP_VERSION}
        HOME: ${HOME_DIR}
    volumes:
    # - ${HOME_DIR}/discoDocker/docker/mail/:/var/mail/
      - /tmp:/tmp
    ports:
      - 1025:1025
      - 1080:8025
    networks:
      - code-network

# SMTP Server - desenvolvimento. (MailDev)
#  maillocal:
#    container_name: maillocal
#    image: maildev/maildev
#    restart: always
#    hostname: maillocal.local
#    command: node bin/maildev --web 80 --smtp 25
#    environment:
#      - HTTP_PORT=yes
#      - SMTP_PORT=yes
#      - VERBOSE=yes
#      - NODE_ENV=production
#    ports:
#      - 1025:25
#      - 1080:80
#    networks:
#      - code-network



  oracledb:
    container_name: oracledb
    #     image: wnameless/oracle-xe-11g
    image: epiclabs/docker-oracle-xe-11g
    ports:
      - "1521:1521"
    networks:
      - code-network

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123456
    networks:
    - code-network

  sonarqube:
    container_name: sonarqube
    image: sonarqube
    restart: always
    ports:
    - 7004:9000
    - 7005:9092
    networks:
    - code-network

volumes:
    phpmyadmin_data:
    php-apache_data:
    mysqldb_data:
    memcached_data:
    portainer_data:
    maillocal_data:
    oracledb_data:
    postgres_data:
    sonarqube_data:

networks:
    code-network:
      driver: bridge


